export const FRONTIER = {
  VALLEY_AND_CRADLE: Symbol("VALLEY_AND_CRADLE"),
  CRADLE_AND_NETWORK: Symbol("CRADLE_AND_NETWORK"),
  NETWORK_AND_LAND: Symbol("NETWORK_AND_LAND"),
  LAND_AND_WILLOW: Symbol("LAND_AND_WILLOW"),
  WILLOW_AND_VALLEY: Symbol("WILLOW_AND_VALLEY"),
};

export const FRONTIER_ORDER = [
  FRONTIER.VALLEY_AND_CRADLE,
  FRONTIER.CRADLE_AND_NETWORK,
  FRONTIER.NETWORK_AND_LAND,
  FRONTIER.LAND_AND_WILLOW,
  FRONTIER.WILLOW_AND_VALLEY,
];

export const FRONTIER_ID = {
  [FRONTIER.VALLEY_AND_CRADLE]: 0,
  [FRONTIER.CRADLE_AND_NETWORK]: 1,
  [FRONTIER.NETWORK_AND_LAND]: 2,
  [FRONTIER.LAND_AND_WILLOW]: 3,
  [FRONTIER.WILLOW_AND_VALLEY]: 4,
};

export const FRONTIER_RANGE = {
  [FRONTIER.VALLEY_AND_CRADLE]: [0, 1, 2],
  [FRONTIER.CRADLE_AND_NETWORK]: [3, 4, 5],
  [FRONTIER.NETWORK_AND_LAND]: [6, 7, 8],
  [FRONTIER.LAND_AND_WILLOW]: [9, 10, 11],
  [FRONTIER.WILLOW_AND_VALLEY]: [12, 13, 14],
};
