export const REALM = {
  VALLEY_OF_MOTIVES: Symbol("VALLEY_OF_MOTIVES"),
  CRADLE_OF_SENSES: Symbol("CRADLE_OF_SENSES"),
  NETWORK_OF_THOUGHTS: Symbol("NETWORK_OF_THOUGHTS"),
  LAND_OF_DESIRES: Symbol("LAND_OF_DESIRES"),
  WILLOW_OF_VALUES: Symbol("WILLOW_OF_VALUES"),
};

export const REALM_ORDER = [
  REALM.VALLEY_OF_MOTIVES,
  REALM.CRADLE_OF_SENSES,
  REALM.NETWORK_OF_THOUGHTS,
  REALM.LAND_OF_DESIRES,
  REALM.WILLOW_OF_VALUES,
];

export const REALM_ID = {
  [REALM.VALLEY_OF_MOTIVES]: 0,
  [REALM.CRADLE_OF_SENSES]: 1,
  [REALM.NETWORK_OF_THOUGHTS]: 2,
  [REALM.LAND_OF_DESIRES]: 3,
  [REALM.WILLOW_OF_VALUES]: 4,
};

export const REALM_RANGE = {
  [REALM.VALLEY_OF_MOTIVES]: [13, 14, 0, 1],
  [REALM.CRADLE_OF_SENSES]: [1, 2, 3, 4],
  [REALM.NETWORK_OF_THOUGHTS]: [4, 5, 6, 7],
  [REALM.LAND_OF_DESIRES]: [7, 8, 9, 10],
  [REALM.WILLOW_OF_VALUES]: [10, 11, 12, 13],
};
