export const SPHERE = {
  COMMITMENT: Symbol("COMMITMENT"),
  CREATIVITY: Symbol("CREATIVITY"),
  HUMILITY: Symbol("HUMILITY"),
  DILIGENCE: Symbol("DILIGENCE"),
  KNOWLEDGE: Symbol("KNOWLEDGE"),
};

export const SPHERE_ORDER = [
  SPHERE.COMMITMENT,
  SPHERE.CREATIVITY,
  SPHERE.HUMILITY,
  SPHERE.DILIGENCE,
  SPHERE.KNOWLEDGE,
];
